title: B. Franklin GIS at UMBC # your name (or website title) here
logo: "/images/Baltimore.jpg?raw=false" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <strong>Undergraduate with background in QGIS and R mapping</strong> at the University of Maryland, Baltimore County
 
  
theme: jekyll-theme-minimal
google_analytics: G-CMRVPKWSBZ # your Google Analytics tracking ID here
